name: playpal
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  appinio_swiper: ^2.1.1
  cloud_firestore: ^5.3.0
  firebase_app_check: ^0.3.0+5
  firebase_auth: ^5.2.0
  firebase_core: ^3.4.0
  firebase_storage: ^12.2.0
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  salomon_bottom_bar: ^3.3.2
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
